/**
 * 图标名称映射工具
 * 将路由配置中的图标名称映射到 Element Plus 图标组件名称
 */

// Element Plus 图标名称映射
const iconMap: Record<string, string> = {
  // 常用图标
  'home': 'HomeFilled',
  'user': 'UserFilled',
  'system': 'Setting',
  'setting': 'Tools',
  'menu': 'Menu',
  'role': 'Avatar',
  'dept': 'OfficeBuilding',
  'peoples': 'Avatar',
  'tree-table': 'Menu',
  'tree': 'OfficeBuilding',
  'cpu': 'Cpu',
  
  // 其他图标映射
  'dashboard': 'Odometer',
  'monitor': 'Monitor',
  'chart': 'PieChart',
  'file': 'Document',
  'folder': 'Folder',
  'search': 'Search',
  'edit': 'Edit',
  'delete': 'Delete',
  'add': 'CirclePlus',
  'save': 'Check',
  'cancel': 'Close',
  'refresh': 'Refresh',
  'download': 'Download',
  'upload': 'Upload',
  'print': 'Printer',
  'mail': 'Message',
  'phone': 'Phone',
  'location': 'Location',
  'time': 'Clock',
  'calendar': 'Calendar',
  'lock': 'Lock',
  'unlock': 'Unlock',
  'eye': 'View',
  'eye-close': 'Hide',
  'star': 'Star',
  'heart': 'Heart',
  'share': 'Share',
  'link': 'Link',
  'external': 'TopRight',
  'back': 'ArrowLeft',
  'forward': 'ArrowRight',
  'up': 'ArrowUp',
  'down': 'ArrowDown',
  'left': 'ArrowLeft',
  'right': 'ArrowRight',
  'expand': 'Expand',
  'collapse': 'Fold',
  'fullscreen': 'FullScreen',
  'exit-fullscreen': 'Close',
  'zoom-in': 'ZoomIn',
  'zoom-out': 'ZoomOut',
  'rotate': 'RefreshRight',
  'filter': 'Filter',
  'sort': 'Sort',
  'grid': 'Grid',
  'list': 'List',
  'card': 'CreditCard',
  'tag': 'PriceTag',
  'label': 'PriceTag',
  'flag': 'Flag',
  'bell': 'Bell',
  'notification': 'Bell',
  'warning': 'Warning',
  'error': 'CircleClose',
  'success': 'CircleCheck',
  'info': 'InfoFilled',
  'question': 'QuestionFilled',
  'help': 'QuestionFilled',
  'tip': 'Lightning',
  'light': 'Sunny',
  'dark': 'Moon',
  'theme': 'Moon',
  'language': 'Globe',
  'translate': 'Globe',
  'code': 'Code',
  'terminal': 'Promotion',
  'database': 'DataBoard',
  'server': 'DataLine',
  'network': 'Connection',
  'cloud': 'Cloudy',
  'wifi': 'Wifi',
  'bluetooth': 'Connection',
  'usb': 'Usb',
  'battery': 'Battery',
  'power': 'SwitchButton',
  'key': 'Key',
  'shield': 'Shield',
  'security': 'Shield',
  'firewall': 'Fire',
  'virus': 'Virus',
  'medical': 'FirstAidKit',
  'health': 'FirstAidKit',
  'education': 'School',
  'school': 'School',
  'book': 'Notebook',
  'library': 'Reading',
  'music': 'Headphone',
  'video': 'VideoCamera',
  'image': 'Picture',
  'camera': 'Camera',
  'mic': 'Microphone',
  'volume': 'Microphone',
  'game': 'Football',
  'sport': 'Football',
  'food': 'Food',
  'drink': 'CoffeeCup',
  'car': 'Van',
  'plane': 'Aircraft',
  'train': 'Train',
  'ship': 'Ship',
  'bike': 'Bicycle',
  'walk': 'Footprint',
  'run': 'Running',
  'sleep': 'MoonNight',
  'weather': 'Sunny',
  'temperature': 'Thermometer',
  'humidity': 'WaterDrop',
  'wind': 'WindPower',
  'rain': 'Umbrella',
  'snow': 'Snowflake',
  'sun': 'Sunny',
  'moon': 'Moon',
  'star': 'Star',
  'planet': 'Planet',
  'rocket': 'Rocket',
  'satellite': 'Satellite',
  'ufo': 'Ufo',
  'robot': 'Robot',
  'ai': 'Cpu',
  'blockchain': 'Link',
  'crypto': 'Coin',
  'money': 'Money',
  'bank': 'BankCard',
  'shopping': 'ShoppingCart',
  'cart': 'ShoppingCart',
  'gift': 'Present',
  'discount': 'Discount',
  'coupon': 'Ticket',
  'invoice': 'DocumentChecked',
  'receipt': 'Receipt',
  'package': 'Box',
  'delivery': 'Truck',
  'logistics': 'Truck',
  'warehouse': 'House',
  'factory': 'Factory',
  'construction': 'Construction',
  'tools': 'Tools',
  'hammer': 'Hammer',
  'wrench': 'Setting',
  'screwdriver': 'Tools',
  'ruler': 'Ruler',
  'measure': 'Ruler',
  'weight': 'Scale',
  'speed': 'Speed',
  'distance': 'Location',
  'direction': 'Compass',
  'navigation': 'Navigation',
  'map': 'MapLocation',
  'gps': 'Location',
  'compass': 'Compass',
  'radar': 'Radar',
  'sonar': 'Sound',
  'laser': 'Aim',
  'telescope': 'Telescope',
  'microscope': 'Microscope',
  'chemistry': 'ChemicalGlass',
  'physics': 'Atom',
  'biology': 'Leaf',
  'geology': 'Mountain',
  'astronomy': 'Planet',
  'math': 'Calculator',
  'statistics': 'PieChart',
  'algorithm': 'Cpu',
  'programming': 'Code',
  'debug': 'Bug',
  'test': 'Experiment',
  'qa': 'Check',
  'deploy': 'Upload',
  'ci-cd': 'Refresh',
  'docker': 'Box',
  'kubernetes': 'Cluster',
  'aws': 'Cloudy',
  'azure': 'Cloudy',
  'gcp': 'Cloudy',
  'github': 'Star',
  'gitlab': 'Star',
  'bitbucket': 'Star',
  'jenkins': 'Setting',
  'travis': 'Check',
  'circleci': 'Refresh',
  'slack': 'Message',
  'discord': 'ChatDotRound',
  'teams': 'ChatLineRound',
  'zoom': 'VideoCamera',
  'meet': 'VideoCamera',
  'skype': 'Phone',
  'whatsapp': 'Message',
  'telegram': 'Paperclip',
  'wechat': 'ChatRound',
  'qq': 'Smoking',
  'weibo': 'Fire',
  'twitter': 'ChatLineSquare',
  'facebook': 'Share',
  'instagram': 'Camera',
  'youtube': 'VideoPlay',
  'tiktok': 'VideoCamera',
  'linkedin': 'Connection',
  'reddit': 'Fire',
  'pinterest': 'Thumb',
  'snapchat': 'Ghost',
  'spotify': 'Headphone',
  'apple': 'Apple',
  'google': 'Chrome',
  'microsoft': 'Windows',
  'linux': 'Monitor',
  'android': 'Mobile',
  'ios': 'Iphone',
  'windows': 'Windows',
  'mac': 'Monitor',
  'chrome': 'Chrome',
  'firefox': 'Fire',
  'safari': 'Compass',
  'edge': 'Link',
  'opera': 'Odometer',
  'brave': 'Shield',
  'vivaldi': 'Compass',
  'tor': 'Lock',
  'vpn': 'Connection',
  'proxy': 'Refresh',
  'cdn': 'Cloudy',
  'ssl': 'Lock',
  'tls': 'Lock',
  'https': 'Lock',
  'http': 'Unlock',
  'api': 'Connection',
  'rest': 'Refresh',
  'graphql': 'Share',
  'grpc': 'Connection',
  'websocket': 'Connection',
  'socket': 'Connection',
  'mqtt': 'Message',
  'kafka': 'DataLine',
  'redis': 'Database',
  'mongodb': 'Leaf',
  'mysql': 'Database',
  'postgresql': 'Database',
  'sqlite': 'Database',
  'oracle': 'Database',
  'sqlserver': 'Database',
  'elasticsearch': 'Search',
  'solr': 'Sunny',
  'splunk': 'PieChart',
  'datadog': 'Dog',
  'newrelic': 'Chart',
  'sentry': 'Warning',
  'loggly': 'Document',
  'papertrail': 'Paperclip',
  'graylog': 'Message',
  'fluentd': 'DataLine',
  'logstash': 'Filter',
  'kibana': 'PieChart',
  'grafana': 'Chart',
  'prometheus': 'Fire',
  'thanos': 'Infinity',
  'loki': 'Search',
  'tempo': 'Clock',
  'jaeger': 'Search',
  'zipkin': 'Location',
  'opentelemetry': 'Connection',
  'opentracing': 'Share',
  'istio': 'Ship',
  'linkerd': 'Link',
  'consul': 'House',
  'etcd': 'Database',
  'zookeeper': 'Tree',
  'nats': 'PaperPlane',
  'rabbitmq': 'Rabbit',
  'activemq': 'DataLine',
  'artemis': 'Sunny',
  'pulsar': 'Star',
  'rocketmq': 'Rocket',
  'nsq': 'Message',
  'zeromq': 'Message',
  'nanomsg': 'Message',
  'mangos': 'Leaf',
}

/**
 * 获取正确的图标组件名称
 * @param iconName 路由配置中的图标名称
 * @returns Element Plus 图标组件名称
 */
export function getIconComponentName(iconName: string): string {
  if (!iconName) return 'Link' // 默认图标
  
  // 如果已经是有效的图标名称，直接返回
  if (iconName.match(/^[A-Z]/)) {
    return iconName
  }
  
  // 从映射表中查找
  return iconMap[iconName.toLowerCase()] || 'Link'
}

/**
 * 检查图标是否有效
 * @param iconName 图标名称
 * @returns 是否有效
 */
export function isValidIcon(iconName: string): boolean {
  if (!iconName) return false
  
  // 检查是否是有效的图标名称
  const validIcon = getIconComponentName(iconName)
  return validIcon !== 'Link' || iconName === 'Link'
}

/**
 * 获取所有可用的图标名称
 * @returns 图标名称列表
 */
export function getAvailableIcons(): string[] {
  return Object.keys(iconMap)
}

export default {
  getIconComponentName,
  isValidIcon,
  getAvailableIcons
}